version: '3'

services:
  flaskApp:
    build: .
    ports:
      - "8001:8001"    
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
